export const fields = {
    plateNo : {name: "plateNo", label: "Plate Number"},
    plateType: {name: "plateType", label: "Plate Type"},
    branch: {name: "branch", label: "Branch"},
    vehicleBrand: {name: "vehicleBrand", label: "Vehicles Brand"},
    model: {name: "model", label: "Model"},
    year: {name: "year", label: "Year"},
    serialNo: {name: "serialNo", label: "Serial Number"},
    vehicleNo: {name: "vehicleNo", label: "Vehicle Number"},
    color: {name: "color", label: "Color"},
    secondaryColor: {name: "secondaryColor", label: "Secondary Color"},
    vehState: {name: "vehState", label: "Vehicles State"},
    licenceEndDt: {name: "licenceEndDt", label: "Licence End Date"},
    checkupEndDt: {name: "checkupEndDt", label: "Checkup End Date"},
    checkupState: {name: "checkupState", label: "Checkup State"},
    insuranceState: {name: "insuranceState", label: "Insurance State"},
    currentUserId: {name: "currentUserId", label: "Current User Personnel Number"},
}

export const initialValues = {
    plateNo : "",
    plateType: "",
    branch: "",
    vehicleBrand: "",
    model: "",
    year: "",
    serialNo: "",
    vehicleNo: "",
    color: "",
    secondaryColor: "",
    vehState: "",
    licenceEndDt: "",
    checkupEndDt: "",
    checkupState: "",
    insuranceState: "",
    currentUserId: "",
}