export var initialValues = {
    personnelNo: '',
    englishName: '',
    arabicName: '',
    nationality: '',
    contractProf: '',
    religion: '',
    hiringType: '',
    phoneNo: '',
    legalProf: '',
    email: '',
    workerType: '',
    legalEntity: '',
    jobTitles: '',
    ContractDuration: '',
    ContractEndDt: '',
    IqamaProfession: "",
    AramcoID: "",
    SEC_ID: "",
    BranchName: "",
    CampLocation: "",
    empTypeId:""

}

export var fields = {
    personnelNo : {name: "personnelNo", label: "Personnel Number"},
    englishName: {name: "englishName", label: "English Name"},
    arabicName: {name: "arabicName", label: "Arabic Name"},
    nationality: {name: "nationality", label: "Nationality"},
    contractProf: {name: "contractProf", label: "Contract Profession"},
    religion: {name: "religion", label: "Religion"},
    hiringType: {name: "hiringType", label: "Hiring Type"},
    phoneNo: {name: "phoneNo", label: "Phone Number"},
    legalProf: {name: "legalProf", label: "Legal Profession"},
    email: {name: "email", label: "Email"},
    workerType: {name: "workerType", label: "Worker Type"},
    legalEntity: {name: "legalEntity", label: "Legal Entity"},
    jobTitles: {name: "jobTitles", label: "Job Titles"},
    ContractDuration: {name: "ContractDuration", label: "Contract Duration"},
    ContractEndDt: {name: "ContractEndDt", label: "Contract End Date"},
    IqamaProfession: {name: "IqamaProfession", label: "Iqama Profession"},
    AramcoID: {name: "AramcoID", label: "Aramco ID"},
    SEC_ID: {name: "SEC_ID", label: "SEC ID"},
    BranchName: {name: "BranchName", label: "Branch Name"},
    CampLocation: {name: "CampLocation", label: "Camp Location"},
    empTypeId:{name: "empTypeId", label: "Employee Type"}
}